runtime: nodejs16

handlers:
  - url: /static
    static_dir: build/static
    secure: always

  - url: /(.*\.(json|ico|js|png))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js|png)$
    secure: always

  - url: .*
    static_files: build/index.html
    upload: build/index.html
    secure: always

env_variables:
  REACT_APP_SERVER_URL: "https://history-course-interface.ue.r.appspot.com/api"