runtime: nodejs16

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html

  - url: /
    static_dir: build

env_variables:
  REACT_APP_SERVER_URL: "https://api-dot-hist-courses.ue.r.appspot.com"